sudo: required

language: generic

notifications:
  email: false

services:
  - docker

before_install:
  - docker pull goofacz/omnetpp-inet-travis:latest

script:
  - docker run -i -t -v /home/travis/build/$TRAVIS_REPO_SLUG:/root/repository goofacz/omnetpp-inet-travis:latest
